import ArticleTemplate from "@/components/blog/ArticleTemplate";

const SLUG = "why-vibe-coded-websites-dont-rank-google";
const TITLE = "Why vibe-coded websites don't rank on Google (and what to do about it)";
const META_DESCRIPTION =
  "You built a beautiful product with Lovable, Bolt, or v0. It looks great. But it's invisible on Google. Here's the technical reason — and how to fix it.";
const PUBLISHED_AT = "2026-03-14";
const AUTHOR = "AutoPilot Geo Team";

const HTML_CONTENT = `
<p>You built a beautiful product with Lovable, Bolt, or v0. It looks great. But it's invisible on Google. Here's the technical reason — and how to fix it.</p>

<h2>The core problem: Googlebot and JavaScript</h2>

<p>When Googlebot visits a SPA, it sees an almost empty HTML file. The actual content — your landing page, blog posts, pricing — only appears after JavaScript executes. Googlebot may not wait for this. Or it may render it incorrectly.</p>

<p>This isn't a bug you introduced. It's the fundamental architecture of every Vite + React app generated by Lovable, Bolt, and v0. Your code is fine. Your <em>delivery method</em> is invisible to Google.</p>

<h2>The 5 reasons vibe-coded sites don't rank</h2>

<div class="issue-card">
  <strong>Issue 1 — No server-side rendering (SSR)</strong>
  <p>Lovable, Bolt, and v0 generate Vite + React apps. Everything renders client-side. Google sees an empty shell. Your homepage content, meta title, and meta description are invisible until JavaScript loads.</p>
</div>

<div class="issue-card">
  <strong>Issue 2 — Fake routing: all paths return the same page</strong>
  <p>In a SPA, <code>/pricing</code>, <code>/blog</code>, and <code>/about</code> all return the same HTML file. Google sees one page, not many. You lose all potential for multi-page indexing.</p>
</div>

<div class="issue-card">
  <strong>Issue 3 — A 2MB+ JavaScript bundle</strong>
  <p>Vibe-coded apps ship everything in one massive JS file. This destroys Core Web Vitals — especially LCP (Largest Contentful Paint). Google's ranking algorithm directly uses page speed. A slow site ranks lower, period.</p>
</div>

<div class="issue-card">
  <strong>Issue 4 — Missing sitemap, robots.txt, and structured data</strong>
  <p>AI coding tools rarely generate a <code>sitemap.xml</code>, a proper <code>robots.txt</code>, or JSON-LD structured data. Google has no map to follow. It doesn't know what pages exist or what your site is about.</p>
</div>

<div class="issue-card">
  <strong>Issue 5 — Blog articles that don't actually exist as pages</strong>
  <p>Auto-generated articles published to a SPA blog are loaded dynamically from a database. Google may never crawl them. Each article needs its own static, pre-rendered HTML URL to be indexable.</p>
</div>

<h2>The real-world proof</h2>

<p>These aren't hypotheticals. They're what happens to every Lovable or Bolt project that goes live without addressing rendering:</p>

<ul>
  <li><strong>0</strong> avg. pages indexed by Google after 30 days</li>
  <li><strong>2.2MB</strong> typical JS bundle size (should be under 200KB)</li>
  <li><strong>1</strong> HTML page seen by Googlebot — for the entire site</li>
</ul>

<p>Google Search Console shows "Crawled — currently not indexed" or "Discovered — currently not indexed" for nearly every URL. The site exists. Google just refuses to show it.</p>

<h2>How to fix it without rebuilding everything</h2>

<h3>Option A — Cloudflare Worker + Prerender (fast, no rebuild)</h3>

<p>Add a Cloudflare Worker that detects bots (Googlebot, GPTBot, etc.) and serves them a pre-rendered HTML version from a Supabase Edge Function. Humans get your SPA as normal. Bots get fully rendered HTML.</p>

<p>Tags: <strong>No rebuild needed</strong> · <strong>Works today</strong> · Requires Cloudflare setup</p>

<p>This is the fastest path. You keep your existing Lovable/Bolt app exactly as-is. You just intercept bot traffic and serve them static HTML snapshots. It takes a few hours to set up and works immediately.</p>

<h3>Option B — Migrate to Next.js with Claude Code (thorough)</h3>

<p>Use Claude Code to migrate your Vite/React SPA to Next.js 14 with App Router. This gives you true SSR, static page generation, proper routing, and optimal bundle splitting. Takes 1–2 days but fixes the root cause permanently.</p>

<p>Tags: <strong>Fixes root cause</strong> · <strong>Best long-term SEO</strong> · 1–2 days of work</p>

<h3>Don't forget: sitemap.xml and robots.txt</h3>

<p>Whichever option you choose, add these two files immediately. Without a sitemap, Google discovers your pages slowly and randomly. Without a proper <code>robots.txt</code>, crawl budget is wasted on irrelevant paths.</p>

<pre><code># sitemap.xml — tell Google every URL that exists
# robots.txt — tell Google what to crawl</code></pre>

<h2>Conclusion</h2>

<p>Vibe coding is genuinely great for shipping fast. Lovable, Bolt, and v0 let one person build in days what used to take a team weeks. But they all share the same SEO blind spot: client-side rendering.</p>

<p>Your product isn't invisible because it's bad. It's invisible because Googlebot can't see it. Fix the delivery layer — with a Cloudflare prerender or a Next.js migration — and the content you've built will finally get the traffic it deserves.</p>
`;

export const metadata = {
  title: `${TITLE} | AutoPilot Geo`,
  description: META_DESCRIPTION,
  openGraph: {
    title: TITLE,
    description: META_DESCRIPTION,
    type: "article",
    publishedTime: PUBLISHED_AT,
    url: `https://autopilotgeo.com/blog/${SLUG}`,
    images: [
      {
        url: "https://autopilotgeo.com/og-vibe-coding-seo.png",
        width: 1200,
        height: 630,
        alt: TITLE,
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: TITLE,
    description: META_DESCRIPTION,
    images: ["https://autopilotgeo.com/og-vibe-coding-seo.png"],
  },
  alternates: {
    canonical: `https://autopilotgeo.com/blog/${SLUG}`,
  },
  robots: "index, follow",
};

export default function Page() {
  return (
    <ArticleTemplate
      title={TITLE}
      htmlContent={HTML_CONTENT}
      metaDescription={META_DESCRIPTION}
      publishedAt={PUBLISHED_AT}
      slug={SLUG}
      author={AUTHOR}
    />
  );
}
